### ISSUE TITLE
Wrong NUMA node initialization causes failure on devices attached to non-0 NUMA node

### ISSUE THREAD

**Issue by dimaruinskiy-intel** [Microsoft/Network-Adapter-Class-Extension#19]
The problem is with the code here:
https://github.com/microsoft/Network-Adapter-Class-Extension/blob/de9490339b44f888aa2b302dc971f76789876950/netcx/adapter/nxadapter.cpp#L3081-L3083

1. _preferredNumaNode_ is a **ULONG** initialized to MM_ANY_NODE_OK (**0x80000000**).
2. _IoGetDeviceNumaNode_ gets a pointer to the address of _preferredNumaNode_ **as USHORT**
3. _IoGetDeviceNumaNode_ overwrites just the bottom word with the actual NUMA node (for example 1).
4. Now _preferredNumaNode_ has an invalid value of **0x80000001**, which is stored in the Tx/Rx memory constraints structures.
5. Down the road it causes a failure in: https://github.com/microsoft/Network-Adapter-Class-Extension/blob/de9490339b44f888aa2b302dc971f76789876950/netcx/bm/dmaallocator.cpp#L62

Confirmed by looking at NetAdapterCx traces:
_BufferManager::AllocateBufferVector - ERROR: Returning STATUS_INSUFFICIENT_RESOURCES. (bufferVector == nullptr is true).
NetClientCreateBufferPool -  [status=0xc000009a(STATUS_INSUFFICIENT_RESOURCES)]
NxTxXlat::Create -  [status=0xc000009a(STATUS_INSUFFICIENT_RESOURCES)]
NxTxXlat::Create -  [status=0xc000009a(STATUS_INSUFFICIENT_RESOURCES)]
QueueControl::CreateQueues -  [status=0xc000009a(STATUS_INSUFFICIENT_RESOURCES)]
NxTranslationApp::CreateDatapath -  [status=0xc000009a(STATUS_INSUFFICIENT_RESOURCES)]
NetClientAdapterSetDeviceFailed - Translator initiated WdfDeviceSetFailed: 0xc000009a(STATUS_INSUFFICIENT_RESOURCES)_

**Note**: this bug will only be visible if the I/O device NUMA node is non-zero. If its zero, the value will stay as MM_ANY_NODE_OK, which does not cause problems with the internal memory allocator routines.

**Comment by amrutha-chandramohan** [comment]
Thanks for reporting this issue - the fix will be in windows insider builds version 26003+
