### ISSUE TITLE
NetAdapterCx is not working in safe mode with networking

### ISSUE THREAD

**Issue by niref** [Microsoft/Network-Adapter-Class-Extension#20]
Hi,

When we boot to safe mode with networking on Windows 11 (build 22621) there is a YB on all network devices that based on NetAdapterCx framework.

Notes:
1) We tested multiple devices and the YB observed (Code 37) only with Netadapter drivers. when we switched to NDIS drivers the YB disappeared.
2) The YB disappeared from Netadapter drivers when we configured netadaptercx start value (under services) to 0 (Boot) instead of 3 (Manual)

It looks like netadaptercx.sys is not starting automatically in safe mode with networking, and as a result all network devices that based on netadaptercx will have a YB in device manager (Code 37)

I have uploaded SetupAPI log for the following flow:

0) Boot to OS in Safe mode with networking
1) Uninstall I226 Netadapter driver (e2fn, 2.1.4.2 whql)
2) Install I226 Netadapter driver (e2fn, 2.1.4.2 whql)
3) YB observed (Code 37) in Device Manager.

[setupapi.dev.log](https://github.com/microsoft/Network-Adapter-Class-Extension/files/13509926/setupapi.dev.log)

Can you please take a look on this issue?

Thanks,
Nir

**Comment by tylerretzlaff** [comment]
framework drivers were not available when running safe mode with networking. should be fixed starting with insider builds 26066 and newer.

thank you for reporting.
