### ISSUE TITLE
NxConfiguration::QueryUlong() does not correctly validate the type of the data returned from NdisWdfReadConfiguration().

### ISSUE THREAD

**Issue by andrew-lee** [Microsoft/Network-Adapter-Class-Extension#6]
The code at [lines 367-368 of nxconfiguration.cpp](https://github.com/Microsoft/Network-Adapter-Class-Extension/blob/4f41254b14fce9be6484e50262823dabc3798989/cx/sys/nxconfiguration.cpp#L367-L368) should be checking `ndisConfigurationParam->ParameterType` rather than `ndisParamType`. The fix should be something like:

```C
if ((NdisParameterInteger != ndisConfigurationParam->ParameterType) &&
    (NdisParameterHexInteger != ndisConfigurationParam->ParameterType)) {
```

**Comment by GabrielGravena** [comment]
Hi Andrew, thanks for reporting this issue. It will be fixed in the next release of Windows.

**Comment by tylerretzlaff** [comment]
hi andrew,

thank you again for reporting the issue it should now be resolved with the recent import of the windows 10 april 2018 update (build 1803)
