### ISSUE TITLE
NxDevice::WdmPnPIrpPreProcess crashes on remove following a failed device start

### ISSUE THREAD

**Issue by kobykahane** [microsoft/Network-Adapter-Class-Extension#7]
We have a KMDF class filter driver that enforces a configurable device blocking policy by failing `EvtDevicePrepareHardware` for disallowed devices. When a filter driver in a device stack fails in 'prepare hardware', the PnP Manager subsequently sends a remove request to the device stack. When the FDO for the device stack uses NetAdapterCx, this causes a BSOD due to access violation while accessing an uninitialized remove lock:

```
00 d6e09834 ae059942 nt!IoAcquireRemoveLockEx+0xc
01 (Inline) -------- NetAdapterCx!Mx::MxAcquireRemoveLock+0x14 [internal\minwin\priv_sdk\inc\wdf\framework\shared\inc\primitives\km\mxgeneralkm.h @ 267] 
02 d6e0985c ae059b03 NetAdapterCx!NxDevice::WdmPnPIrpPreProcess+0x32 [minio\ndis\cx\sys\nxdevice.cpp @ 1685] 
03 d6e09878 86afd8c7 NetAdapterCx!EvtWdmPnpPowerIrpPreprocessRoutine+0x81 [minio\ndis\cx\sys\nxdevice.cpp @ 1806] 
04 (Inline) -------- Wdf01000!PreprocessIrp+0x38d94 [minkernel\wdf\framework\shared\core\fxdevice.cpp @ 1506] 
05 (Inline) -------- Wdf01000!DispatchWorker+0x39081 [minkernel\wdf\framework\shared\core\fxdevice.cpp @ 1565] 
06 (Inline) -------- Wdf01000!FxDevice::Dispatch+0x39087 [minkernel\wdf\framework\shared\core\fxdevice.cpp @ 1586] 
07 d6e098d8 81695f48 Wdf01000!FxDevice::DispatchWithLock+0x390d7 [minkernel\wdf\framework\shared\core\fxdevice.cpp @ 1430] 
08 d6e098f0 8198c10c nt!IofCallDriver+0x48
09 d6e0992c 81b60960 nt!IopSynchronousCall+0xa8
0a d6e09988 81806564 nt!IopRemoveDevice+0xe3
0b d6e099b4 81b4387e nt!PnpRemoveLockedDeviceNode+0x206
0c d6e099c8 81b43978 nt!PnpDeleteLockedDeviceNode+0x60
0d d6e09a08 81b584b7 nt!PnpDeleteLockedDeviceNodes+0x9e
0e d6e09a80 81ae80be nt!PnpProcessQueryRemoveAndEject+0x3f4
0f d6e09aa0 81a09185 nt!PnpProcessTargetDeviceEvent+0xc8bbc
10 d6e09ae4 816ad146 nt!PnpDeviceEventWorker+0x19f
11 d6e09b38 816f8b52 nt!ExpWorkerThread+0x156
12 d6e09b70 81788c2d nt!PspSystemThreadStartup+0x4a
13 d6e09b7c 00000000 nt!KiThreadStartup+0x15
```

This happens because the handler for `IRP_MN_REMOVE_DEVICE` attempts to acquire the remove lock: https://github.com/microsoft/Network-Adapter-Class-Extension/blob/release_1903/cx/sys/nxdevice.cpp#L2305
But the remove lock is only initialized after a successful construction of `NxDevice` at https://github.com/microsoft/Network-Adapter-Class-Extension/blob/release_1903/cx/sys/nxdevice.cpp#L655
An `NxDevice` is only constructed if upper filters did not fail 'prepare hardware' and the FDO is performing it: https://github.com/microsoft/Network-Adapter-Class-Extension/blob/release_1903/cx/sys/nxdevice.cpp#L722

I believe this is a bug in NetAdapterCx - a driver should be robust to an `IRP_MN_REMOVE_DEVICE` arriving after the device stack failed to start due to an upper filter failing 'prepare hardware' or any other phase of device start, since the PnP Manager sends such a remove in those cases.

A full crash dump is available upon request, but I believe the issue is evident without it.

**Comment by brandonjiang** [comment]
Hey, Koby, Thanks for reporting this issue. We have confirmed it's indeed a bug in NetAdapterCx, and we will fix it in the upcoming Windows release

**Comment by kobykahane** [comment]
Thanks @brandonjiang . I assume this means 20H1. Is there any chance for this to be serviced in previous Windows releases?

**Comment by brandonjiang** [comment]
@kobykahane please send email to netadapter@microsoft.com for servicing discussion
