### ISSUE TITLE
Windows 11/2xxxx Insider builds

### ISSUE THREAD

**Issue by trametheka** [Microsoft/Network-Adapter-Class-Extension#9]
Any news on updates for the Dev ring insider builds? NetAdapterCx has seemed to need updates for the Dev channel Insider builds for some time now, however nothing has been committed here or updated in the docs. Was hoping there would be an update with the release of the Windows 11 insider builds.

Cheers.

**Comment by brandonjiang** [comment]
Hey, we have plan to update the repo soon when Windows 11 is officially released
